#!/bin/bash

(cd webroot && python3 -m http.server 8080 -b 127.0.0.1) &

while true; do
    xinit ./ENTRYX -- -retro -dpms
    echo "Terminated exit code $?"
    echo "10 seconds to restart..."
    sleep 10
done
