#!/bin/sh

export PATH=/sbin:/bin
mkdir -p /proc /sys /dev /mnt/boot /mnt/root /mnt/rw /mnt/ro
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
bootdev=/dev/mmcblk0p1
for i in $(cat /proc/cmdline); do
        case $i in
                bootdev=*) bootdev=${i#*=} ;;
        esac
done
for i in 1 2 3 4 5; do
        test -b $bootdev && break
        sleep 1
done
if ! mount $bootdev /mnt/boot -o ro; then
        setsid cttyhack sh
fi
mount /mnt/boot/boot/rootfs.squashfs /mnt/ro -o loop,ro -t squashfs
chroot /mnt/ro modprobe overlay
mount -t tmpfs tmpfs /mnt/rw
mkdir /mnt/rw/upper /mnt/rw/work
mount -t overlay -o lowerdir=/mnt/ro,upperdir=/mnt/rw/upper,workdir=/mnt/rw/work overlay /mnt/root
mkdir -p /mnt/root/overlay/rw /mnt/root/overlay/ro
mount --move /mnt/boot /mnt/root/boot
mount --move /mnt/rw /mnt/root/overlay/rw
mount --move /mnt/ro /mnt/root/overlay/ro
if test -x /mnt/root/bin/sh; then
        exec switch_root /mnt/root /bin/systemd
else
        echo "Set up failed!"
        exec sh
fi
